# Generated by Django 4.1.1 on 2022-10-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requisite',
            field=models.ManyToManyField(blank=True, to='course.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='code',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
