# Generated by Django 4.1.1 on 2022-10-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pre_requisite',
            field=models.ManyToManyField(blank=True, null=True, to='course.course'),
        ),
    ]
