# Generated by Django 4.1.1 on 2022-11-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_department_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='description',
        ),
    ]
