# Generated by Django 4.1.1 on 2022-10-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_pre_requisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_requisite',
            field=models.ManyToManyField(blank=True, to='course.course'),
        ),
    ]
