# Generated by Django 4.1.1 on 2022-10-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_pre_requisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='code',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
