# Generated by Django 4.1.1 on 2022-12-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
