# Generated by Django 4.1.1 on 2022-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_historicalstudyplan_studyplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperiodacademic',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperiodacademic',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodacademic',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodacademic',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='course.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_requisite',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='course.course'),
        ),
    ]
