# Generated by Django 4.1.1 on 2022-12-07 01:34

import apps.portafolio.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_name_en_historicalcourse_name_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portafolio', '0003_historicalform_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=120)),
                ('path', models.FileField(upload_to=apps.portafolio.models.file_path, verbose_name='file resource')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.folder')),
                ('period_academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.periodacademic')),
            ],
            options={
                'verbose_name': 'File_Resource',
                'verbose_name_plural': 'File_Resources',
                'db_table': 'file_resource',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFileResource',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Created Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=120)),
                ('path', models.TextField(max_length=100, verbose_name='file resource')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.course')),
                ('folder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portafolio.folder')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period_academic', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.periodacademic')),
            ],
            options={
                'verbose_name': 'historical File_Resource',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='course',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='period_academic',
        ),
        migrations.DeleteModel(
            name='HistoricalResource',
        ),
        migrations.AlterField(
            model_name='historicalportfolio',
            name='resource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portafolio.fileresource'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.fileresource'),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
