# Generated by Django 4.1.1 on 2022-10-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_alter_historicalpermission_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='historicalpermission',
            name='fatherPermission',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='fatherPermission',
        ),
        migrations.AddField(
            model_name='permission',
            name='sonPermissions',
            field=models.ManyToManyField(blank=True, to='user.permission'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='user.role', verbose_name='role'),
        ),
    ]
