# Generated by Django 4.1.1 on 2022-10-13 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_curriculumvitae_historicalcurriculumvitae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id_user'),
        ),
        migrations.AlterField(
            model_name='historicalcurriculumvitae',
            name='id_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='id_user'),
        ),
    ]
