# Generated by Django 4.1.1 on 2022-11-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_name_historicaluser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='edit',
            field=models.BooleanField(default=True),
        ),
    ]
