# Generated by Django 4.1.1 on 2022-10-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_curriculumvitae_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermission',
            name='edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='edit',
            field=models.BooleanField(default=True),
        ),
    ]
