# Generated by Django 4.1.1 on 2022-10-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_name_historicaluser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermission',
            name='isFather',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='isFather',
            field=models.BooleanField(default=False),
        ),
    ]
