# Generated by Django 4.1.1 on 2022-10-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_historicalpermission_edit_permission_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpermission',
            name='fatherPermission',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='fatherPermission',
        ),
        migrations.AddField(
            model_name='permission',
            name='sonPermissions',
            field=models.ManyToManyField(blank=True, to='user.permission'),
        ),
    ]
