# Generated by Django 4.1.1 on 2022-12-09 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_fileresource_historicalfileresource_and_more'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsyllabusabetform',
            name='form',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portafolio.form'),
        ),
        migrations.AddField(
            model_name='syllabusabetform',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portafolio.form'),
        ),
    ]
