# Generated by Django 4.1.1 on 2022-10-31 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='levelDescription',
        ),
        migrations.AlterField(
            model_name='criteria',
            name='student_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='student.studentresult'),
        ),
    ]
