# Generated by Django 4.1.1 on 2022-12-04 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0006_remove_criteria_leveldescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentresult',
            name='study_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.studyplan'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='study_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.studyplan'),
        ),
    ]