# Generated by Django 4.1.1 on 2022-12-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_add_studyplan_studentresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleveldescription',
            name='criteria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='student.criteria'),
        ),
        migrations.AddField(
            model_name='leveldescription',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.criteria'),
        ),
    ]