# Generated by Django 4.1.1 on 2022-12-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_criteria_leveldescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencies',
            name='description_en',
            field=models.CharField(blank=True, max_length=380, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompetencies',
            name='description_en',
            field=models.CharField(blank=True, max_length=380, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudentresult',
            name='description_en',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='description_en',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='competencies',
            name='description',
            field=models.CharField(max_length=380, null=True),
        ),
        migrations.AlterField(
            model_name='competencies',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompetencies',
            name='description',
            field=models.CharField(max_length=380, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompetencies',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentresult',
            name='description',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='description',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
