# Generated by Django 4.1.1 on 2022-12-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_add_matchcoursecompetence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentresult',
            name='description',
            field=models.CharField(max_length=540, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentresult',
            name='description_en',
            field=models.CharField(blank=True, max_length=540, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='description',
            field=models.CharField(max_length=540, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='description_en',
            field=models.CharField(blank=True, max_length=540, null=True),
        ),
    ]
